### ISSUE TITLE
基础CNN网络那节matplotlib显示数字有错

### ISSUE THREAD

**Issue by 1219521375** [czy36mengfei/tensorflow2_tutorials_chinese#1]
```python
import matplotlib.pyplot as plt
plt.imshow(x_train[0])
plt.show()
```
似乎是之前下载的数组格式是(28，28，1)，reshape为(28，28)就可以正常显示

**Comment by czy36mengfei** [comment]
谢谢，当时在构造2d卷积时发现原输入少了一维，加了reshape((-1,28,28,1)),加错地方了，已修改

原代码
![image](https://user-images.githubusercontent.com/16059497/56175838-869ff180-602b-11e9-9e8c-8e77a55ec288.png)
修改后代码
![image](https://user-images.githubusercontent.com/16059497/56175757-26a94b00-602b-11e9-8f74-f335a72fe08e.png)
