### ISSUE TITLE
tf2.0训练速度慢于1.x

### ISSUE THREAD

**Issue by aimetrics** [czy36mengfei/tensorflow2_tutorials_chinese#2]
Hi, @czy36mengfei 请问你有和tf1.0对比过训练的速度吗? 我这边看是不管用keras的optimizer来训练还是用GradientTape + tf.function，2.0的速度都显著慢于1.x，大概慢了2.5倍

**Comment by czy36mengfei** [comment]
我这边在cpu跑并没有发现这个问题。
下面是我用keras实现的一个text_cnn的文本分类训练情况：

  | 训练1 | 训练2
-- | -- | --
  | epoch1 | epoch2 | epoch1 | epoch2
tf1.11 | 28s | 30s | 32s | 33s
tf2.0 | 21s | 23s | 21s | 22s

**Comment by KANGRuipeng** [comment]
@czy36mengfei  可以给个分类的2.0例子吗？我自己的1.14快于2.0，比例也差不多是2.5倍

**Comment by 123Mrxiao** [comment]
你好，邮件我已收到！现在繁忙稍后回复。

**Comment by jiandandema** [comment]
谢谢您给马坤发送邮件，我会及时查看的，谢谢，辛苦了
