### ISSUE TITLE
batch() and step_per_epoch

### ISSUE THREAD

**Issue by Student-HXJ** [czy36mengfei/tensorflow2_tutorials_chinese#5]
```
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(64)

val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(64)

# model.fit(train_dataset, epochs=3)
# steps_per_epoch 每个epoch只训练几步
# validation_steps 每次验证，验证几步
model.fit(train_dataset, epochs=3, steps_per_epoch=100,
         validation_data=val_dataset, validation_steps=3)
```

你好，请问model.fit 里面的batch_size （epochs/step_per_epoch）是不是会覆盖掉前面的train_dataset.batch(64) ?

**Comment by czy36mengfei** [comment]
使用dataset的的话，fit里面不能写batch_size,steps_per_epoch是个epoch时间训练几个batch，所以整个epoch可以不用训练完全部数据，epoch本身就是要填的

**Comment by Student-HXJ** [comment]
所以model.fit里面使用的batch是之前设置的64 而不是我说的（epochs/steps_per_epoch）是这样吧？

还有如果我设置的steps_per_epoch如果超出了一个epoch的数据量的范围，
eg: epoch1[1,2,3],  epoch2[2,1,3]
那么训练是继续下一个epoch呢？ [1,2,3,2,1,3]
还是从本次epoch的数据从第一个样本开始继续循环？[1,2,3,1,2,3]
还是会截止到本次epoch数据的最后一个样本？[1,2,3]

**Comment by czy36mengfei** [comment]
> 所以model.fit里面使用的batch是之前设置的64 而不是我说的（epochs/steps_per_epoch）是这样吧？
> 
> 还有如果我设置的steps_per_epoch如果超出了一个epoch的数据量的范围，
> eg: epoch1[1,2,3], epoch2[2,1,3]
> 那么训练是继续下一个epoch呢？ [1,2,3,2,1,3]
> 还是从本次epoch的数据从第一个样本开始继续循环？[1,2,3,1,2,3]
> 还是会截止到本次epoch数据的最后一个样本？[1,2,3]

嗯，就是之前设置的batch_size.
用repeat重复数据，应该是读完数据接着重头开始读（就像把数据构造成一个环，最后一个结束，接着从新回到第一个），所以应该是[1,2,3,1,2,3]

**Comment by Student-HXJ** [comment]
谢谢解答
